created the new merchant page
bukkaApp/Mybukka-Frontend pull request #92
Opened 2020-04-10 15:12 UTC by ufas-001

#### What does this PR do?
<Brief Message Usually Ticket Title>
created the new merchant page
#### Description of the task to be completed?
- created the page with route /merchant
- point 2
- point 3

#### How can this manually be tested?
- clone this repo
```
$ git clone https://github.com/bukkaApp/Mybukka-Frontend
```
- install all dependencies
```
$ npm i
```
- start Application
```
$ npm start:dev
```
- log on to _localhost:PORT_ to interact with created page

#### Any background context you want to provide?

#### Relevant PT story(ies)
<PT_STORY_ID>

#### Screenshots (if appropriate)

#### Questions
N/A

2020-04-20 17:39 UTC, akolliy1 requested changes
Great, You just need to make a few changes and proper indentation.

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/common/customButton.jsx
> +import '../index.scss'
Are sure of this file `import './CustomButton.scss';` should be small letter `c`. And why do you have index styling imported here

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/common/customButton.jsx
> +);
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/common/customButton.scss
> +}
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/banner.jsx
> +    </div>
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/banner.scss
> +    padding-top: 30px;
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/banner.scss
> +}
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/description.css
> +}
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/footer.jsx
> +);
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/navDescription.css
> +}
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/navDescription.jsx
> +    </div>
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/orderDescription.css
> +}
2 spaces indentation

2020-04-20 17:39 UTC, akolliy1 commented on src/features/merchantPage/component/presenceDesccription.jsx
> +    </div>
2 spaces indentation

2020-04-21 15:24 UTC, ufas-001 commented
I don't think 2 space indentation is achievable for css and scss. Waiting
for your feedback before I push

On Mon, Apr 20, 2020 at 6:39 PM Adesanmi Akolade dotun <
notifications@github.com> wrote:

> *@akolliy1* requested changes on this pull request.
>
> Great, You just need to make a few changes and proper indentation.
> ------------------------------
>
> In src/features/merchantPage/common/customButton.jsx
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409545437>
> :
>
> > +import './CustomButton.scss';
>
> +import '../index.scss'
>
>
> Are sure of this file import './CustomButton.scss'; should be small
> letter c. And why do you have index styling imported here
> ------------------------------
>
> In src/features/merchantPage/common/customButton.jsx
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409545902>
> :
>
> > +const CustomButton = ({ buttonChildren, spanChildren }) => (
>
> +    <div>
>
> +        <button className="custom-button mt-3">{buttonChildren}</button> <span className="custom-span">{spanChildren}</span>
>
> +    </div>
>
> +);
>
>
> 2 spaces indentation
> ------------------------------
>
> In src/features/merchantPage/common/customButton.scss
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409546173>
> :
>
> > +.custom-span {
>
> +    font-family: Roboto;
>
> +    font-style: normal;
>
> +    font-weight: normal;
>
> +    font-size: 18px;
>
> +    line-height: 24px;
>
> +    color: #949494;
>
> +}
>
> +
>
> +.custom-button {
>
> +    background: #F5E7D8;
>
> +    border-radius: 5px;
>
> +    width: 132px;
>
> +    height: 51px;
>
> +    border: 1px solid #F5E7D8;
>
> +    font-family: Roboto;
>
> +    font-style: normal;
>
> +    font-weight: normal;
>
> +    font-size: 20px;
>
> +    line-height: 23px;
>
> +    text-align: center;
>
> +    color: #9D1621;
>
> +}
>
>
> 2 spaces indentation
> ------------------------------
>
> In src/features/merchantPage/component/banner.jsx
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409546939>
> :
>
> > +const Banner = () => (
>
> +    <div className="banner">
>
> +        <img className="banner-img"
>
> +        src='https://res.cloudinary.com/mybukka/image/upload/v1586431637/edgar-castrejon-1SPu0KT-Ejg-unsplash_z4vudy.jpg' alt="banner" />
>
> +        <div className="banner-info">
>
> +            <div className="info-content">
>
> +                <Logo />
>
> +                <div>
>
> +                    <button className="log-in-btn">log in</button>
>
> +                    <button className="sign-up-btn">sign up</button>
>
> +                </div>
>
> +            </div>
>
> +            <div className="content">
>
> +                <h4>Grow Your Takeout Sales by 200%</h4>
>
> +                <p>With the top 3rd-party delivery platform for customer spend and retention.</p>
>
> +                <div className="text-align-center">
>
> +                    <button className="get-started-btn">Get started</button>
>
> +                </div>
>
> +            </div>
>
> +        </div>
>
> +    </div>
>
>
> 2 spaces indentation
> ------------------------------
>
> In src/features/merchantPage/component/banner.scss
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409547411>
> :
>
> > +.banner-img {
>
> +    height: 600px;
>
> +    width: 100%;
>
> +    object-fit: cover;
>
> +    position: relative;
>
> +}
>
> +
>
> +.banner-info {
>
> +    position: absolute;
>
> +    background: rgba(0, 0, 0, 0.8);
>
> +    width: 100%;
>
> +    height: 600px;
>
> +    top: 0px;
>
> +}
>
> +
>
> +.info-content {
>
> +    width: 90%;
>
> +    display: flex;
>
> +    justify-content: space-between;
>
> +    padding-top: 30px;
>
>
> 2 spaces indentation
> ------------------------------
>
> In src/features/merchantPage/component/banner.scss
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409547862>
> :
>
> > +.log-in-btn {
>
> +    background: rgba(0, 0, 0, 0.8);
>
> +    border: 1px solid #ffff;
>
> +    box-sizing: border-box;
>
> +    border-radius: 30px;
>
> +    padding: 5px 19px;
>
> +    text-transform: uppercase;
>
> +    font-weight: normal;
>
> +    font-size: 12px;
>
> +    color: #ffff;
>
> +    font-family: 'Roboto', sans-serif;
>
> +    margin-right: 10px;
>
> +    cursor: pointer;
>
> +}
>
> +
>
> +.sign-up-btn {
>
> +    background: #9D1621;
>
> +    border: 1px solid #9D1621;
>
> +    box-sizing: border-box;
>
> +    border-radius: 30px;
>
> +    padding: 5px 19px;
>
> +    text-transform: uppercase;
>
> +    font-weight: normal;
>
> +    font-size: 12px;
>
> +    color: #ffff;
>
> +    font-family: 'Roboto', sans-serif;
>
> +    cursor: pointer;
>
> +}
>
> +
>
> +.content {
>
> +    margin-top: 130px;
>
> +}
>
> +
>
> +.content h4 {
>
> +    width: 40%;
>
> +    font-family: Roboto;
>
> +    font-weight: bold;
>
> +    font-size: 40px;
>
> +    line-height: 47px;
>
> +    color: #ffff;
>
> +    margin: auto;
>
> +    text-align: center;
>
> +    margin-top: 20px;
>
> +}
>
> +
>
> +.content p {
>
> +    width: 40%;
>
> +    font-family: Roboto;
>
> +    font-weight: bold;
>
> +    font-size: 16px;
>
> +    line-height: 19px;
>
> +    color: #ffff;
>
> +    margin: auto;
>
> +    text-align: center;
>
> +    margin-top: 20px;
>
> +}
>
> +
>
> +.get-started-btn {
>
> +    background: #9D1621;
>
> +    border: 1px solid #9D1621;
>
> +    box-sizing: border-box;
>
> +    border-radius: 30px;
>
> +    padding: 13px 29px;
>
> +    text-transform: uppercase;
>
> +    font-weight: normal;
>
> +    font-size: 15px;
>
> +    color: #ffff;
>
> +    font-family: 'Roboto', sans-serif;
>
> +    cursor: pointer;
>
> +    line-height: 18px;
>
> +    margin-top: 30px;
>
> +    margin-bottom: 20px;
>
> +}
>
>
> 2 spaces indentation
> ------------------------------
>
> In src/features/merchantPage/component/description.css
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409548392>
> :
>
> > +.description {
>
> +    text-align: center;
>
> +    margin-top: 30px;
>
> +}
>
> +
>
> +.description h4 {
>
> +    font-family: Roboto;
>
> +    font-style: normal;
>
> +    font-weight: 900;
>
> +    font-size: 35px;
>
> +    line-height: 41px;
>
> +}
>
> +
>
> +.description p {
>
> +    font-family: Roboto;
>
> +    font-style: normal;
>
> +    font-weight: normal;
>
> +    font-size: 18px;
>
> +    line-height: 21px;
>
> +    color: #949494;
>
> +}
>
> +
>
> +.bar {
>
> +    content: '';
>
> +    width: 69px;
>
> +    height: 7px;
>
> +    background: #9D1621;
>
> +    margin-top: 20px;
>
> +    text-align: center;
>
> +    margin: auto;
>
> +}
>
> +
>
> +.custom-icon {
>
> +    color: #9D1621;
>
> +    border-radius: 50%;
>
> +    background: rgba(157, 22, 33, 0.2);
>
> +    width: 70px;
>
> +    height: 70px;
>
> +    line-height: 70px !important;
>
> +}
>
> +
>
> +.description-info h4 {
>
> +    font-family: Roboto;
>
> +    font-style: normal;
>
> +    font-weight: 900;
>
> +    font-size: 22px;
>
> +    line-height: 26px;
>
> +}
>
> +
>
> +.description-info p {
>
> +    font-family: Roboto;
>
> +    font-style: normal;
>
> +    font-weight: normal;
>
> +    font-size: 18px;
>
> +    line-height: 24px;
>
> +    text-align: center;
>
> +    color: #949494;
>
> +    width: 220px;
>
> +    margin: auto;
>
> +}
>
>
> 2 spaces indentation
> ------------------------------
>
> In src/features/merchantPage/component/footer.jsx
> <https://github.com/bukkaApp/Mybukka-Frontend/pull/92#discussion_r409604470>
> :
>
> > +const Footer = () => (
>
> +    <div class="footer pt-4 pb-4">
>
> +        <div class="container">
>
> +            <div class="row txt-white">
>
> +                <div class="bukka-description col-md-4 f-16 height-19">
>
> +                    <Logo />
>
> +                    <div class="pt-5 txt-white">
>
> +                        <p>The largest, most reliable on-demand delivery and pickup platform.</p>
>
> +                        <p class="pt-2">Able to deliver  [...]

2020-09-10 19:23 UTC, closed without merging